language: cpp

env:
  global:
    # Ubuntu version
    - LINUX_DIST=trusty
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    # Global build options and C++ flags
    - CXX_FLAGS="-Wall -pedantic -Werror -Wno-variadic-macros -Wno-long-long -Wno-shadow"
    # Misc
    - RUN_TESTS=true
    - COVERAGE=false

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: true
      compiler: gcc
      addons:
       apt:
         packages: &precise_latest_boost_packages
           - gcc-4.8
           - g++-4.8
           #- gcov-4.9
           #- clang-3.7
           #- valgrind
           # Misc
           #- python-yaml
           - lcov
           #- libopencv-dev
         sources: &precise_latest_boost_sources
           - ubuntu-toolchain-r-test
           - llvm-toolchain-precise-3.7
         artifacts: true  
    
before_install:
    # Combine global build options with OS/compiler-dependent options
    - export CMAKE_OPTIONS=${CMAKE_OPTIONS}" "${ENV_CMAKE_OPTIONS}
    - export CXX_FLAGS=${CXX_FLAGS}" "${ENV_CXX_FLAGS}

install:
    - if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
    - echo ${PATH}
    - echo ${CXX}
    - ${CXX} --version
    - ${CXX} -v
    - sudo pip install codecov
    
    # Download and install recent cmake
    - |
      if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
        CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.1-Linux-x86_64.tar.gz"
        mkdir -p ${DEPS_DIR}/cmake
        travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
        export PATH=${DEPS_DIR}/cmake/bin:${PATH}
      fi
script:
     - ./build.sh

 
     
deploy:
  provider: releases
  #api_key: 
  #  secure: 12345678
  #github_token: 897d37cbeb4825b4cbb4d7383cfe151d39fb0046
  api_token:
    secure: szoCgA0Qpue+xe24PAY/F03iTI6OOV1dM8XY9kDMMPMCJ+CZfy7Yq8yv1ixT3mTadFERiixSETVP7D4ErUoUEYRsNB/y97LwYKlCj4rOd58VxD04tsD/tyc4XmC7qUEeXFy3kSWHRfupUsBYzKmVMy3ozU+1Tra8lJd6+BfbGAq54kr9sVdQCN85aYwBu/2R+FfLNoS3GHwjXmmNEYT9YpInIV/y8CeKwTFXecVWdLPRe2sLgl8tmrKUaGqDWYPtlwswd3oqguJKHvnYxgYpcTqwv7aYQn9N0n4ESoewhPCAA7i6KcKm/oIcuPqGlxuue3ibRVnQ9pXGm2eP3CX+cn19E6kAHDyPInWDZlf+2mWfbJt/PtgwUgj56qaOShScWBUV5oP/AkBrZ67U4txLmCNy716O4c0NpBCwKLEYJj41SIEfhNFHyF7kaqIEzr6ZCckU+r2cUjHqD3wjXjTS/umNU3INJgK3ShihZz6i9r0KCQGB7boHv29i37+UxOqH8rr+taOkMdqSGnOibeyn7+xQzaYfzCuS2xzPgYJb10Msakf1Qh/O8qwEPvQ+Ty4BicSBCGxguaN0Z6fiwViGlPgbcxZKh/dXALBgBwh4BV5ixWXcUTX5RD90dhufytKm6pknLgM1vHZ3upFQYk38RPEJRML+Bv88JiLXfR17VY0=
  file: build/test
  skip_cleanup: true
  draft: true    
  local_dir: build
  on:
    branch: master
   # tags: true
    
